### ISSUE TITLE
Crash datadog_screenboard - setJSONNumberToDict():  is not convertible to float

### ISSUE THREAD

**Issue by nagaharayuuki** [terraform-providers/terraform-provider-datadog#116]
After updating to v1.5.0 crash has occurred on part of screenboard.
"panic: setJSONNumberToDict (): is not convertible to float" is the cause.

### Terraform Version
```
$ terraform -v
Terraform v0.11.10
+ provider.aws v1.43.2
+ provider.datadog v1.5.0
+ provider.template v1.0.0
```

### Affected Resource(s)
- datadog_screenboard

### Terraform Configuration Files
```hcl
resource "datadog_screenboard" "cloudfront" {
  title     = "CloudFront"
  read_only = true

  template_variable {
    name    = "scope"
    default = "*"
  }

  template_variable {
    name   = "distributionid"
    prefix = "distributionid"
  }

  # Title
  widget {
    type       = "note"
    x          = 1
    y          = 1
    height     = 20
    width      = 20
    bgcolor    = "gray"
    text_align = "center"
    font_size  = 36
    tick       = false
    html       = "CloudFront"
  }

  # Traffic
  widget {
    type       = "note"
    x          = 22
    y          = 1
    height     = 20
    width      = 20
    bgcolor    = "gray"
    text_align = "left"
    font_size  = 36
    tick       = true
    tick_edge  = "right"
    tick_pos   = "50%"
    html       = "Traffic"
  }

  ### Request Cout
  widget {
    type   = "timeseries"
    x      = 22
    y      = 22
    height = 18
    width  = 40
    title  = "Request Count"

    tile_def {
      viz = "timeseries"

      request {
        q    = "avg:aws.cloudfront.requests{$scope,$distributionid} by {distributionid}.as_count()"
        type = "line"
      }
    }
  }

  ### Bytes Downloaded
  widget {
    type   = "timeseries"
    x      = 22
    y      = 63
    height = 18
    width  = 40
    title  = "Bytes Downloaded"

    tile_def {
      viz = "timeseries"

      request {
        q    = "avg:aws.cloudfront.bytes_downloaded{$scope,$distributionid} by {distributionid}.as_count()"
        type = "line"
      }
    }
  }

  ### Bytes Uploaded
  widget {
    type   = "timeseries"
    x      = 22
    y      = 104
    height = 18
    width  = 40
    title  = "Bytes Uploaded"

    tile_def {
      viz = "timeseries"

      request {
        q    = "avg:aws.cloudfront.bytes_uploaded{$scope,$distributionid} by {distributionid}.as_count()"
        type = "line"
      }
    }
  }

  # Error
  widget {
    type       = "note"
    x          = 43
    y          = 1
    height     = 20
    width      = 20
    bgcolor    = "gray"
    text_align = "left"
    font_size  = 36
    tick       = true
    tick_edge  = "right"
    tick_pos   = "50%"
    html       = "Error"
  }

  ### 4xx Error Rate
  widget {
    type   = "timeseries"
    x      = 43
    y      = 22
    height = 18
    width  = 40
    title  = "4xx Error Rate"

    tile_def {
      viz = "timeseries"

      request {
        q    = "avg:aws.cloudfront.4xx_error_rate{$scope,$distributionid} by {distributionid}"
        type = "line"
      }
    }
  }

  ### 5xx Error Rate
  widget {
    type   = "timeseries"
    x      = 43
    y      = 63
    height = 18
    width  = 40
    title  = "5xx Error Rate"

    tile_def {
      viz = "timeseries"

      request {
        q    = "avg:aws.cloudfront.5xx_error_rate{$scope,$distributionid} by {distributionid}"
        type = "line"
      }
    }
  }
}
```
I did not divide which widget it is.

### Panic Output
```
2018-11-12T09:01:38.032+0900 [DEBUG] plugin.terraform-provider-datadog_v1.5.0_x4: panic: setJSONNumberToDict():  is not convertible to float
2018-11-12T09:01:38.032+0900 [DEBUG] plugin.terraform-provider-datadog_v1.5.0_x4:
2018-11-12T09:01:38.032+0900 [DEBUG] plugin.terraform-provider-datadog_v1.5.0_x4: goroutine 43 [running]:
2018-11-12T09:01:38.032+0900 [DEBUG] plugin.terraform-provider-datadog_v1.5.0_x4: github.com/terraform-providers/terraform-provider-datadog/datadog.setJSONNumberToDict(0xc4204bc390, 0x19d0417, 0x9, 0xc420167c40)
2018-11-12T09:01:38.032+0900 [DEBUG] plugin.terraform-provider-datadog_v1.5.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-datadog/datadog/resource_datadog_screenboard.go:1007 +0x1b8
2018-11-12T09:01:38.032+0900 [DEBUG] plugin.terraform-provider-datadog_v1.5.0_x4: github.com/terraform-providers/terraform-provider-datadog/datadog.setToDict(0xc4204bc390, 0x19d0417, 0x9, 0x18d18a0, 0xc420167c40)
2018-11-12T09:01:38.032+0900 [DEBUG] plugin.terraform-provider-datadog_v1.5.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-datadog/datadog/resource_datadog_screenboard.go:1032 +0x350
2018-11-12T09:01:38.032+0900 [DEBUG] plugin.terraform-provider-datadog_v1.5.0_x4: github.com/terraform-providers/terraform-provider-datadog/datadog.batchSetToDict(0xc4204bc390, 0xc4206a67b8, 0xa, 0xa)
2018-11-12T09:01:38.032+0900 [DEBUG] plugin.terraform-provider-datadog_v1.5.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-datadog/datadog/resource_datadog_screenboard.go:1042 +0x61
2018-11-12T09:01:38.032+0900 [DEBUG] plugin.terraform-provider-datadog_v1.5.0_x4: github.com/terraform-providers/terraform-provider-datadog/datadog.buildTFTileDef(0xc42041a480, 0xc4204bc2d0, 0x19cb725, 0x4)
2018-11-12T09:01:38.032+0900 [DEBUG] plugin.terraform-provider-datadog_v1.5.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-datadog/datadog/resource_datadog_screenboard.go:1187 +0x1d4
2018-11-12T09:01:38.032+0900 [DEBUG] plugin.terraform-provider-datadog_v1.5.0_x4: github.com/terraform-providers/terraform-provider-datadog/datadog.buildTFWidget(0xc420167af0, 0xc42055bcc2, 0xc420167b40, 0xc420167a50, 0xc42055bcb8, 0xc42055bc98, 0xc42055bd68, 0xc42055bd38, 0xc42055bd48, 0xc4203fa1a8, ...)
2018-11-12T09:01:38.032+0900 [DEBUG] plugin.terraform-provider-datadog_v1.5.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-datadog/datadog/resource_datadog_screenboard.go:1325 +0xa38
2018-11-12T09:01:38.032+0900 [DEBUG] plugin.terraform-provider-datadog_v1.5.0_x4: github.com/terraform-providers/terraform-provider-datadog/datadog.resourceDatadogScreenboardRead(0xc4201deaf0, 0x19c8120, 0xc420178980, 0xc4201deaf0, 0x0)
2018-11-12T09:01:38.032+0900 [DEBUG] plugin.terraform-provider-datadog_v1.5.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-datadog/datadog/resource_datadog_screenboard.go:1358 +0x590
2018-11-12T09:01:38.032+0900 [DEBUG] plugin.terraform-provider-datadog_v1.5.0_x4: github.com/terraform-providers/terraform-provider-datadog/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc42029e460, 0xc4206760f0, 0x19c8120, 0xc420178980, 0xc42015b698, 0x10b9801, 0x182f680)
2018-11-12T09:01:38.032+0900 [DEBUG] plugin.terraform-provider-datadog_v1.5.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-datadog/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:352 +0x167
2018-11-12T09:01:38.033+0900 [DEBUG] plugin.terraform-provider-datadog_v1.5.0_x4: github.com/terraform-providers/terraform-provider-datadog/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0xc42029e5b0, 0xc420676000, 0xc4206760f0, 0x18, 0x18, 0xc4206883c0)
2018-11-12T09:01:38.033+0900 [DEBUG] plugin.terraform-provider-datadog_v1.5.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-datadog/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:308 +0x9a
2018-11-12T09:01:38.033+0900 [DEBUG] plugin.terraform-provider-datadog_v1.5.0_x4: github.com/terraform-providers/terraform-provider-datadog/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Refresh(0xc4204284a0, 0xc42067e060, 0xc42067e2b0, 0x0, 0x0)
2018-11-12T09:01:38.033+0900 [DEBUG] plugin.terraform-provider-datadog_v1.5.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-datadog/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:549 +0x4e
2018-11-12T09:01:38.033+0900 [DEBUG] plugin.terraform-provider-datadog_v1.5.0_x4: reflect.Value.call(0xc420342c00, 0xc42055c200, 0x13, 0x19cb02d, 0x4, 0xc42007ef18, 0x3, 0x3, 0xc4203f2280, 0x0, ...)
2018/11/12 09:01:38 [ERROR] root.dashboard: eval: *terraform.EvalRefresh, err: datadog_screenboard.cloudfront: unexpected EOF
2018/11/12 09:01:38 [ERROR] root.dashboard: eval: *terraform.EvalSequence, err: datadog_screenboard.cloudfront: unexpected EOF
2018/11/12 09:01:38 [TRACE] [walkRefresh] Exiting eval tree: module.dashboard.datadog_screenboard.cloudfront
2018-11-12T09:01:38.033+0900 [DEBUG] plugin.terraform-provider-datadog_v1.5.0_x4: 	/opt/goenv/versions/1.10.3/src/reflect/value.go:447 +0x969
2018-11-12T09:01:38.033+0900 [DEBUG] plugin.terraform-provider-datadog_v1.5.0_x4: reflect.Value.Call(0xc420342c00, 0xc42055c200, 0x13, 0xc420401718, 0x3, 0x3, 0x0, 0x0, 0x0)
2018-11-12T09:01:38.033+0900 [DEBUG] plugin.terraform-provider-datadog_v1.5.0_x4: 	/opt/goenv/versions/1.10.3/src/reflect/value.go:308 +0xa4
2018-11-12T09:01:38.033+0900 [DEBUG] plugin.terraform-provider-datadog_v1.5.0_x4: net/rpc.(*service).call(0xc420168500, 0xc4205668c0, 0xc42055abe0, 0xc42055abf0, 0xc4201d8600, 0xc4203f6540, 0x182f640, 0xc42067e060, 0x16, 0x182f680, ...)
2018-11-12T09:01:38.033+0900 [DEBUG] plugin.terraform-provider-datadog_v1.5.0_x4: 	/opt/goenv/versions/1.10.3/src/net/rpc/server.go:384 +0x14e
2018-11-12T09:01:38.033+0900 [DEBUG] plugin.terraform-provider-datadog_v1.5.0_x4: created by net/rpc.(*Server).ServeCodec
```

### Actual Behavior
We have confirmed that the problem occurs only in v1.5.0 and not in v1.4.0.

### Steps to Reproduce
1. `terraform init && terraform plan`

**Comment by masci** [comment]
Hi @nagaharayuuki thanks a lot for reporting!
I'm closing in favor of #117, let's sync there
