### ISSUE TITLE
A crash or an error occurs in applying for log pipelines

### ISSUE THREAD

**Issue by iwasetechfunjp** [terraform-providers/terraform-provider-datadog#387]
```
$ terraform version
Terraform v0.11.13
+ provider.datadog v2.5.0
```
I'd like to define datadog-logs-custom-pipeline.
In the definition, I coded the below codes.
```
  filter {
    query=""
  }
```
It is purport to construct the pipeline like the below image.
![2020-01-10_14h36_36](https://user-images.githubusercontent.com/23071851/72129198-b3b1e280-33b8-11ea-9e5a-714639c9cd51.png)
![2020-01-10_14h42_44](https://user-images.githubusercontent.com/23071851/72129206-b7456980-33b8-11ea-8eac-f229e6faba22.png)
But, `terraform apply` has crashed.
I tried to apply `filter{query="*"}` next, but error.

> \* datadog_logs_custom_pipeline.xxxx: 1 error(s) occurred:
> 
> \* datadog_logs_custom_pipeline.xxxx: failed to create logs pipeline using Datadog API: API error 400 Bad Request: {"error":{"code":"InvalidArgument","message":"Invalid Pipeline","details":[{"code":"InvalidArgument","message":"Invalid parser"}]}}

---

* terraform crashed log

```
panic: interface conversion: interface {} is nil, not map[string]interface {}
2020-01-10T14:53:43.161+0900 [DEBUG] plugin.terraform-provider-datadog_v2.5.0_x4:
2020/01/10 14:53:43 [TRACE] root: eval: *terraform.EvalWriteState
2020-01-10T14:53:43.170+0900 [DEBUG] plugin.terraform-provider-datadog_v2.5.0_x4: goroutine 385 [running]:
2020-01-10T14:53:43.170+0900 [DEBUG] plugin.terraform-provider-datadog_v2.5.0_x4: github.com/terraform-providers/terraform-provider-datadog/datadog.buildDatadogPipeline(0xc0003256c0, 0x0, 0x0, 0x1115798)
2020-01-10T14:53:43.170+0900 [DEBUG] plugin.terraform-provider-datadog_v2.5.0_x4:       /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-datadog/datadog/resource_datadog_logs_custom_pipeline.go:467 +0x427
2020-01-10T14:53:43.170+0900 [DEBUG] plugin.terraform-provider-datadog_v2.5.0_x4: github.com/terraform-providers/terraform-provider-datadog/datadog.resourceDatadogLogsPipelineCreate(0xc0003256c0, 0x10c84c0, 0xc00058a840, 0x2, 0x1c54c20)
2020-01-10T14:53:43.170+0900 [DEBUG] plugin.terraform-provider-datadog_v2.5.0_x4:       /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-datadog/datadog/resource_datadog_logs_custom_pipeline.go:249 +0x2f
2020-01-10T14:53:43.170+0900 [DEBUG] plugin.terraform-provider-datadog_v2.5.0_x4: github.com/terraform-providers/terraform-provider-datadog/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc000253580, 0xc000aed090, 0xc00077daa0, 0x10c84c0, 0xc00058a840, 0x40b801, 0xc0000b1b80, 0x4c26ec)
2020-01-10T14:53:43.170+0900 [DEBUG] plugin.terraform-provider-datadog_v2.5.0_x4:       /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-datadog/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:286 +0x363
2020-01-10T14:53:43.170+0900 [DEBUG] plugin.terraform-provider-datadog_v2.5.0_x4: github.com/terraform-providers/terraform-provider-datadog/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc000af2b80, 0xc000aed040, 0xc000aed090, 0xc00077daa0, 0xc000054a80, 0xc0000b1b60, 0x7f9a90129000)
2020/01/10 14:53:43 [TRACE] root: eval: *terraform.EvalApplyProvisioners
2020/01/10 14:53:43 [TRACE] root: eval: *terraform.EvalIf
2020/01/10 14:53:43 [TRACE] root: eval: *terraform.EvalWriteState
2020/01/10 14:53:43 [TRACE] root: eval: *terraform.EvalWriteDiff
2020/01/10 14:53:43 [TRACE] root: eval: *terraform.EvalApplyPost
2020-01-10T14:53:43.170+0900 [DEBUG] plugin: plugin process exited: path=/parent directory/.terraform/plugins/linux_amd64/terraform-provider-datadog_v2.5.0_x4
2020-01-10T14:53:43.170+0900 [DEBUG] plugin.terraform-provider-datadog_v2.5.0_x4:       /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-datadog/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:285 +0x9c
2020/01/10 14:53:43 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* datadog_logs_custom_pipeline.yyyy: unexpected EOF
2020/01/10 14:53:43 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* datadog_logs_custom_pipeline.yyyy: unexpected EOF
2020-01-10T14:53:43.170+0900 [DEBUG] plugin.terraform-provider-datadog_v2.5.0_x4: github.com/terraform-providers/terraform-provider-datadog/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Apply(0xc0007969e0, 0xc00077d640, 0xc000394410, 0x0, 0x0)
2020-01-10T14:53:43.170+0900 [DEBUG] plugin.terraform-provider-datadog_v2.5.0_x4:       /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-datadog/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:530 +0x57
2020-01-10T14:53:43.170+0900 [DEBUG] plugin.terraform-provider-datadog_v2.5.0_x4: reflect.Value.call(0xc00008c360, 0xc00069ade8, 0x13, 0x10cba3b, 0x4, 0xc0000b1f18, 0x3, 0x3, 0xc000259000, 0xc0008bf400, ...)
2020-01-10T14:53:43.170+0900 [DEBUG] plugin.terraform-provider-datadog_v2.5.0_x4:       /opt/goenv/versions/1.11.5/src/reflect/value.go:447 +0x454
2020-01-10T14:53:43.170+0900 [DEBUG] plugin.terraform-provider-datadog_v2.5.0_x4: reflect.Value.Call(0xc00008c360, 0xc00069ade8, 0x13, 0xc0004d1f18, 0x3, 0x3, 0x11, 0xc0004d1f28, 0x100010000)
2020-01-10T14:53:43.170+0900 [DEBUG] plugin.terraform-provider-datadog_v2.5.0_x4:       /opt/goenv/versions/1.11.5/src/reflect/value.go:308 +0xa4
2020-01-10T14:53:43.170+0900 [DEBUG] plugin.terraform-provider-datadog_v2.5.0_x4: net/rpc.(*service).call(0xc0007fe580, 0xc000098500, 0xc0005608d0, 0xc0005608e0, 0xc000af2c00, 0xc000796a80, 0xec3d80, 0xc00077d640, 0x16, 0xec3dc0, ...)
2020-01-10T14:53:43.170+0900 [DEBUG] plugin.terraform-provider-datadog_v2.5.0_x4:       /opt/goenv/versions/1.11.5/src/net/rpc/server.go:384 +0x14e
2020-01-10T14:53:43.170+0900 [DEBUG] plugin.terraform-provider-datadog_v2.5.0_x4: created by net/rpc.(*Server).ServeCodec
2020-01-10T14:53:43.170+0900 [DEBUG] plugin.terraform-provider-datadog_v2.5.0_x4:       /opt/goenv/versions/1.11.5/src/net/rpc/server.go:481 +0x47e
2020/01/10 14:53:43 [TRACE] [walkApply] Exiting eval tree: datadog_logs_custom_pipeline.yyyy
2020/01/10 14:53:43 [TRACE] root: eval: *terraform.EvalWriteState
2020/01/10 14:53:43 [TRACE] root: eval: *terraform.EvalApplyProvisioners
2020/01/10 14:53:43 [TRACE] root: eval: *terraform.EvalIf
2020/01/10 14:53:43 [TRACE] root: eval: *terraform.EvalWriteState
2020/01/10 14:53:43 [TRACE] root: eval: *terraform.EvalWriteDiff
2020/01/10 14:53:43 [TRACE] root: eval: *terraform.EvalApplyPost
2020/01/10 14:53:43 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* datadog_logs_custom_pipeline.xxxx: unexpected EOF
2020/01/10 14:53:43 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* datadog_logs_custom_pipeline.xxxx: unexpected EOF
2020/01/10 14:53:43 [TRACE] [walkApply] Exiting eval tree: datadog_logs_custom_pipeline.xxxx
2020/01/10 14:53:43 [TRACE] dag/walk: upstream errored, not walking "meta.count-boundary (count boundary fixup)"
2020/01/10 14:53:43 [TRACE] dag/walk: upstream errored, not walking "provider.datadog (close)"
2020/01/10 14:53:43 [TRACE] dag/walk: upstream errored, not walking "root"
2020/01/10 14:53:43 [TRACE] Preserving existing state lineage "f8f1e44d-3689-8cf9-8dd7-74c3610359e8"
2020/01/10 14:53:43 [TRACE] Preserving existing state lineage "f8f1e44d-3689-8cf9-8dd7-74c3610359e8"
2020/01/10 14:53:43 [TRACE] Preserving existing state lineage "f8f1e44d-3689-8cf9-8dd7-74c3610359e8"
2020/01/10 14:53:43 [DEBUG] Uploading remote state to S3: {
  Body: buffer(0xc00053d530),
  Bucket: "terraform remote state bucket name",
  ContentLength: 110045,
  ContentType: "application/json",
  Key: "state file name"
}
2020/01/10 14:53:43 [DEBUG] plugin: waiting for all plugin processes to complete...
2020-01-10T14:53:43.365+0900 [WARN ] plugin: error closing client during Kill: err="connection is shut down"



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by gzussa** [comment]
This issue should be solve now since we changed the underlying client. Feel free to reopen if you still see the issue.

**Comment by p-tomoya-iwase** [comment]
Thanks for your changing.
I upgraded datadog plugin version to and applied.
```
$ terraform version
Terraform v0.11.13
+ provider.datadog v2.12.1
```

But crash in applying have been still occured.

Reopen this issue.

**Comment by iwasetechfunjp** [comment]
Thanks for your changing.
I upgraded datadog plugin version to and applied.
```
$ terraform version
Terraform v0.11.13
+ provider.datadog v2.12.1
```

But crash in applying have been still occured.

Reopen this issue.

**Comment by therve** [comment]
You can't have a query string that is empty? That's the change I made for #605 . I think you have another error after passing `query="*"` which we can look at. Thanks.
